In [124]:
import pandas as pd

In [125]:
books=pd.read_csv('Books.csv')

C:\Users\iaman\AppData\Local\Temp\ipykernel_13848\2241478042.py:1: DtypeWarning: Columns (3) have mixed types. Specify dtype option on import or set low_memory=False.
  books=pd.read_csv('Books.csv')

books mein kitne unique publishers hain? sirf ek line mein nikaal.

In [127]:
books['Publisher'].nunique()

16807

In [128]:
ratings=pd.read_csv('Ratings.csv')
users=pd.read_csv('Users.csv')

users mein Age column mein kitne null values hain? percentage bhi nikaal total ka.

In [130]:
users[users['Age'].isna()]

        User-ID                            Location  Age
0             1                  nyc, new york, usa  NaN
2             3     moscow, yukon territory, russia  NaN
4             5  farnborough, hants, united kingdom  NaN
6             7                 washington, dc, usa  NaN
7             8            timmins, ontario, canada  NaN
...         ...                                 ...  ...
278849   278850          sergnano, lombardia, italy  NaN
278853   278854               portland, oregon, usa  NaN
278855   278856           brampton, ontario, canada  NaN
278856   278857           knoxville, tennessee, usa  NaN
278857   278858                dublin, n/a, ireland  NaN

[110762 rows x 3 columns]

In [131]:
users[users['Age'].isnull()]

        User-ID                            Location  Age
0             1                  nyc, new york, usa  NaN
2             3     moscow, yukon territory, russia  NaN
4             5  farnborough, hants, united kingdom  NaN
6             7                 washington, dc, usa  NaN
7             8            timmins, ontario, canada  NaN
...         ...                                 ...  ...
278849   278850          sergnano, lombardia, italy  NaN
278853   278854               portland, oregon, usa  NaN
278855   278856           brampton, ontario, canada  NaN
278856   278857           knoxville, tennessee, usa  NaN
278857   278858                dublin, n/a, ireland  NaN

[110762 rows x 3 columns]

ratings mein Book-Rating ki value counts nikaal — kaunsi rating sabse zyada di gayi hai?

In [133]:
ratings['Book-Rating'].value_counts()

Book-Rating
0     716109
8     103736
10     78610
7      76457
9      67541
5      50974
6      36924
4       8904
3       5996
2       2759
1       1770
Name: count, dtype: int64

books mein Year-Of-Publication column ka dtype kya hai? Agar string hai toh numeric mein convert karo aur invalid values (jo number nahi hain) ko NaN bana do.

In [135]:
books

,ISBN,Book-Title,Book-Author,Year-Of-Publication,Publisher,Image-URL-S,Image-URL-M,Image-URL-L
0,0195153448,Classical Mythology,Mark P. O. Morford,2002,Oxford University Press,http://images.amazon.com/images/P/0195153448.0...,http://images.amazon.com/images/P/0195153448.0...,http://images.amazon.com/images/P/0195153448.0...
1,0002005018,Clara Callan,Richard Bruce Wright,2001,HarperFlamingo Canada,http://images.amazon.com/images/P/0002005018.0...,http://images.amazon.com/images/P/0002005018.0...,http://images.amazon.com/images/P/0002005018.0...
2,0060973129,Decision in Normandy,Carlo D'Este,1991,HarperPerennial,http://images.amazon.com/images/P/0060973129.0...,http://images.amazon.com/images/P/0060973129.0...,http://images.amazon.com/images/P/0060973129.0...
3,0374157065,Flu: The Story of the Great Influenza Pandemic...,Gina Bari Kolata,1999,Farrar Straus Giroux,http://images.amazon.com/images/P/0374157065.0...,http://images.amazon.com/images/P/0374157065.0...,http://images.amazon.com/images/P/0374157065.0...
4,0393045218,The Mummies of Urumchi,E. J. W. Barber,1999,W. W. Norton &amp; Company,http://images.amazon.com/images/P/0393045218.0...,http://images.amazon.com/images/P/0393045218.0...,http://images.amazon.com/images/P/0393045218.0...
...,...,...,...,...,...,...,...,...
271355,0440400988,There's a Bat in Bunk Five,Paula Danziger,1988,Random House Childrens Pub (Mm),http://images.amazon.com/images/P/0440400988.0...,http://images.amazon.com/images/P/0440400988.0...,http://images.amazon.com/images/P/0440400988.0...
271356,0525447644,From One to One Hundred,Teri Sloat,1991,Dutton Books,http://images.amazon.com/images/P/0525447644.0...,http://images.amazon.com/images/P/0525447644.0...,http://images.amazon.com/images/P/0525447644.0...
271357,006008667X,Lily Dale : The True Story of the Town that Ta...,Christine Wicker,2004,HarperSanFrancisco,http://images.amazon.com/images/P/006008667X.0...,http://images.amazon.com/images/P/006008667X.0...,http://images.amazon.com/images/P/006008667X.0...
271358,0192126040,Republic (World's Classics),Plato,1996,Oxford University Press,http://images.amazon.com/images/P/0192126040.0...,http://images.amazon.com/images/P/0192126040.0...,http://images.amazon.com/images/P/0192126040.0...
271359,0767409752,A Guided Tour of Rene Descartes' Meditations o...,Christopher Biffle,2000,McGraw-Hill Humanities/Social Sciences/Languages,http://images.amazon.com/images/P/0767409752.0...,http://images.amazon.com/images/P/0767409752.0...,http://images.amazon.com/images/P/0767409752.0...

In [136]:
books['Year-Of-Publication'].dtype

dtype('O')

In [137]:
books.head(2)

,ISBN,Book-Title,Book-Author,Year-Of-Publication,Publisher,Image-URL-S,Image-URL-M,Image-URL-L
0,0195153448,Classical Mythology,Mark P. O. Morford,2002,Oxford University Press,http://images.amazon.com/images/P/0195153448.0...,http://images.amazon.com/images/P/0195153448.0...,http://images.amazon.com/images/P/0195153448.0...
1,0002005018,Clara Callan,Richard Bruce Wright,2001,HarperFlamingo Canada,http://images.amazon.com/images/P/0002005018.0...,http://images.amazon.com/images/P/0002005018.0...,http://images.amazon.com/images/P/0002005018.0...

In [138]:
books['Year-Of-Publication'] = pd.to_numeric(
    books['Year-Of-Publication'],
    errors='coerce'
)
#errors='coerce' -> invalid strings ko forcefully NaN bana deta hai ✅

users ki Location column se sirf country nikaal (last part after last comma) aur ek naya column 'Country' banao.

In [140]:
users

        User-ID                            Location   Age
0             1                  nyc, new york, usa   NaN
1             2           stockton, california, usa  18.0
2             3     moscow, yukon territory, russia   NaN
3             4           porto, v.n.gaia, portugal  17.0
4             5  farnborough, hants, united kingdom   NaN
...         ...                                 ...   ...
278853   278854               portland, oregon, usa   NaN
278854   278855  tacoma, washington, united kingdom  50.0
278855   278856           brampton, ontario, canada   NaN
278856   278857           knoxville, tennessee, usa   NaN
278857   278858                dublin, n/a, ireland   NaN

[278858 rows x 3 columns]

In [141]:
users['Location']

0                         nyc, new york, usa
1                  stockton, california, usa
2            moscow, yukon territory, russia
3                  porto, v.n.gaia, portugal
4         farnborough, hants, united kingdom
                         ...
278853                 portland, oregon, usa
278854    tacoma, washington, united kingdom
278855             brampton, ontario, canada
278856             knoxville, tennessee, usa
278857                  dublin, n/a, ireland
Name: Location, Length: 278858, dtype: object

In [142]:
users['Location'].str.split(',')

0                         [nyc,  new york,  usa]
1                  [stockton,  california,  usa]
2            [moscow,  yukon territory,  russia]
3                  [porto,  v.n.gaia,  portugal]
4         [farnborough,  hants,  united kingdom]
                           ...
278853                 [portland,  oregon,  usa]
278854    [tacoma,  washington,  united kingdom]
278855             [brampton,  ontario,  canada]
278856             [knoxville,  tennessee,  usa]
278857                  [dublin,  n/a,  ireland]
Name: Location, Length: 278858, dtype: object

In [143]:
users['Location'].str.split(',').str[-1]

0                     usa
1                     usa
2                  russia
3                portugal
4          united kingdom
               ...
278853                usa
278854     united kingdom
278855             canada
278856                usa
278857            ireland
Name: Location, Length: 278858, dtype: object

In [144]:
#Extra spaces hatao using str.strip()
users['Location'].str.split(',').str[-1].str.strip()

0                    usa
1                    usa
2                 russia
3               portugal
4         united kingdom
               ...
278853               usa
278854    united kingdom
278855            canada
278856               usa
278857           ireland
Name: Location, Length: 278858, dtype: object

In [145]:
users['country']=users['Location'].str.split(',').str[-1].str.strip()

In [146]:
users.head(2)

   User-ID                   Location   Age country
0        1         nyc, new york, usa   NaN     usa
1        2  stockton, california, usa  18.0     usa

Har author ne kitni books likhi hain? Top 10 authors dikhao jo sabse zyada books likhe hain.

In [148]:
books

,ISBN,Book-Title,Book-Author,Year-Of-Publication,Publisher,Image-URL-S,Image-URL-M,Image-URL-L
0,0195153448,Classical Mythology,Mark P. O. Morford,2002.0,Oxford University Press,http://images.amazon.com/images/P/0195153448.0...,http://images.amazon.com/images/P/0195153448.0...,http://images.amazon.com/images/P/0195153448.0...
1,0002005018,Clara Callan,Richard Bruce Wright,2001.0,HarperFlamingo Canada,http://images.amazon.com/images/P/0002005018.0...,http://images.amazon.com/images/P/0002005018.0...,http://images.amazon.com/images/P/0002005018.0...
2,0060973129,Decision in Normandy,Carlo D'Este,1991.0,HarperPerennial,http://images.amazon.com/images/P/0060973129.0...,http://images.amazon.com/images/P/0060973129.0...,http://images.amazon.com/images/P/0060973129.0...
3,0374157065,Flu: The Story of the Great Influenza Pandemic...,Gina Bari Kolata,1999.0,Farrar Straus Giroux,http://images.amazon.com/images/P/0374157065.0...,http://images.amazon.com/images/P/0374157065.0...,http://images.amazon.com/images/P/0374157065.0...
4,0393045218,The Mummies of Urumchi,E. J. W. Barber,1999.0,W. W. Norton &amp; Company,http://images.amazon.com/images/P/0393045218.0...,http://images.amazon.com/images/P/0393045218.0...,http://images.amazon.com/images/P/0393045218.0...
...,...,...,...,...,...,...,...,...
271355,0440400988,There's a Bat in Bunk Five,Paula Danziger,1988.0,Random House Childrens Pub (Mm),http://images.amazon.com/images/P/0440400988.0...,http://images.amazon.com/images/P/0440400988.0...,http://images.amazon.com/images/P/0440400988.0...
271356,0525447644,From One to One Hundred,Teri Sloat,1991.0,Dutton Books,http://images.amazon.com/images/P/0525447644.0...,http://images.amazon.com/images/P/0525447644.0...,http://images.amazon.com/images/P/0525447644.0...
271357,006008667X,Lily Dale : The True Story of the Town that Ta...,Christine Wicker,2004.0,HarperSanFrancisco,http://images.amazon.com/images/P/006008667X.0...,http://images.amazon.com/images/P/006008667X.0...,http://images.amazon.com/images/P/006008667X.0...
271358,0192126040,Republic (World's Classics),Plato,1996.0,Oxford University Press,http://images.amazon.com/images/P/0192126040.0...,http://images.amazon.com/images/P/0192126040.0...,http://images.amazon.com/images/P/0192126040.0...
271359,0767409752,A Guided Tour of Rene Descartes' Meditations o...,Christopher Biffle,2000.0,McGraw-Hill Humanities/Social Sciences/Languages,http://images.amazon.com/images/P/0767409752.0...,http://images.amazon.com/images/P/0767409752.0...,http://images.amazon.com/images/P/0767409752.0...

In [149]:
books['Book-Author']

0           Mark P. O. Morford
1         Richard Bruce Wright
2                 Carlo D'Este
3             Gina Bari Kolata
4              E. J. W. Barber
                  ...
271355          Paula Danziger
271356              Teri Sloat
271357        Christine Wicker
271358                   Plato
271359     Christopher  Biffle
Name: Book-Author, Length: 271360, dtype: object

In [150]:
books.groupby('Book-Author')

In [151]:
books.groupby('Book-Author').size()

Book-Author
 D. Chiel                           1
 J. D. Landis                       1
 Mimma Balia                        1
'N Sync                             1
142 moms from all over the world    1
                                   ..
Â¢ystein LÂ²nn                      1
Ã?dÃ¶n von HorvÃ¡th                 3
Ã?Â?dÃ?Â¶n von Horvath              1
Ã?Â?pictÃ?Â¨te                      1
Ã?Â?ric Holder                      1
Length: 102022, dtype: int64

In [152]:
books.groupby('Book-Author').size().sort_values(ascending=False)

Book-Author
Agatha Christie                632
William Shakespeare            567
Stephen King                   524
Ann M. Martin                  423
Carolyn Keene                  373
                              ...
margaret Sidney                  1
m Craig Barnes                   1
le Philosophe SÃ?Â©nÃ?Â¨que      1
l. Daniels                       1
ky                               1
Length: 102022, dtype: int64

In [153]:
#Top 10 authors
books.groupby('Book-Author').size().sort_values(ascending=False).head(10)

Book-Author
Agatha Christie        632
William Shakespeare    567
Stephen King           524
Ann M. Martin          423
Carolyn Keene          373
Francine Pascal        372
Isaac Asimov           330
Nora Roberts           315
Barbara Cartland       307
Charles Dickens        302
dtype: int64

In [154]:
users

        User-ID                            Location   Age         country
0             1                  nyc, new york, usa   NaN             usa
1             2           stockton, california, usa  18.0             usa
2             3     moscow, yukon territory, russia   NaN          russia
3             4           porto, v.n.gaia, portugal  17.0        portugal
4             5  farnborough, hants, united kingdom   NaN  united kingdom
...         ...                                 ...   ...             ...
278853   278854               portland, oregon, usa   NaN             usa
278854   278855  tacoma, washington, united kingdom  50.0  united kingdom
278855   278856           brampton, ontario, canada   NaN          canada
278856   278857           knoxville, tennessee, usa   NaN             usa
278857   278858                dublin, n/a, ireland   NaN         ireland

[278858 rows x 4 columns]

In [155]:
ratings

         User-ID         ISBN  Book-Rating
0         276725   034545104X            0
1         276726   0155061224            5
2         276727   0446520802            0
3         276729   052165615X            3
4         276729   0521795028            6
...          ...          ...          ...
1149775   276704   1563526298            9
1149776   276706   0679447156            0
1149777   276709   0515107662           10
1149778   276721   0590442449           10
1149779   276723  05162443314            8

[1149780 rows x 3 columns]

Har user ne total kitni ratings di hain? Top 5 most active users nikaal.↓
Har user ke ratings count karo

In [157]:
ratings.groupby('User-ID')['Book-Rating'].count()

User-ID
2          1
7          1
8         18
9          3
10         2
          ..
278846     2
278849     4
278851    23
278852     1
278854     8
Name: Book-Rating, Length: 105283, dtype: int64

In [158]:
ratings.groupby('User-ID')['Book-Rating'].count().sort_values(ascending=False).head(5)

User-ID
11676     13602
198711     7550
153662     6109
98391      5891
35859      5850
Name: Book-Rating, dtype: int64

In [159]:
users

        User-ID                            Location   Age         country
0             1                  nyc, new york, usa   NaN             usa
1             2           stockton, california, usa  18.0             usa
2             3     moscow, yukon territory, russia   NaN          russia
3             4           porto, v.n.gaia, portugal  17.0        portugal
4             5  farnborough, hants, united kingdom   NaN  united kingdom
...         ...                                 ...   ...             ...
278853   278854               portland, oregon, usa   NaN             usa
278854   278855  tacoma, washington, united kingdom  50.0  united kingdom
278855   278856           brampton, ontario, canada   NaN          canada
278856   278857           knoxville, tennessee, usa   NaN             usa
278857   278858                dublin, n/a, ireland   NaN         ireland

[278858 rows x 4 columns]

In [160]:
ratings.groupby('User-ID')['Book-Rating'].count()
#har user ne kitni entries (ratings)

User-ID
2          1
7          1
8         18
9          3
10         2
          ..
278846     2
278849     4
278851    23
278852     1
278854     8
Name: Book-Rating, Length: 105283, dtype: int64

In [161]:
ratings.groupby('User-ID')['Book-Rating'].count().sort_values(ascending=False).head(5)

User-ID
11676     13602
198711     7550
153662     6109
98391      5891
35859      5850
Name: Book-Rating, dtype: int64

Har ISBN ki average rating nikaal — sirf woh ISBNs rakho jinhe minimum 100 ratings mili ho. Result ko avg rating ke basis pe sort karo descending mein.ratings

In [163]:
ratings

         User-ID         ISBN  Book-Rating
0         276725   034545104X            0
1         276726   0155061224            5
2         276727   0446520802            0
3         276729   052165615X            3
4         276729   0521795028            6
...          ...          ...          ...
1149775   276704   1563526298            9
1149776   276706   0679447156            0
1149777   276709   0515107662           10
1149778   276721   0590442449           10
1149779   276723  05162443314            8

[1149780 rows x 3 columns]

In [164]:
ratings.groupby('ISBN')['Book-Rating'].count()

ISBN
 0330299891    2
 0375404120    2
 0586045007    1
 9022906116    2
 9032803328    1
              ..
cn113107       1
ooo7156103     1
§423350229     1
´3499128624    1
Ô½crosoft      1
Name: Book-Rating, Length: 340556, dtype: int64

In [165]:
#Har ISBN ke ratings count nikalo
isbn_counts = ratings.groupby('ISBN')['Book-Rating'].count()

In [166]:
isbn_counts[isbn_counts>=100]

ISBN
002542730X    171
0060008032    104
0060096195    107
006016848X    147
0060173289    130
             ...
1573227331    105
1573229326    217
1573229571    106
1592400876    120
1878424319    133
Name: Book-Rating, Length: 731, dtype: int64

In [167]:
isbn_counts[isbn_counts>=100]

ISBN
002542730X    171
0060008032    104
0060096195    107
006016848X    147
0060173289    130
             ...
1573227331    105
1573229326    217
1573229571    106
1592400876    120
1878424319    133
Name: Book-Rating, Length: 731, dtype: int64

In [168]:
valid_isbns = isbn_counts[isbn_counts >= 100].index

In [169]:
valid_isbns

Index(['002542730X', '0060008032', '0060096195', '006016848X', '0060173289',
       '0060175400', '006019491X', '0060199652', '0060391626', '0060392452',
       ...
       '1558744630', '1558745157', '1559029838', '1573225517', '1573225789',
       '1573227331', '1573229326', '1573229571', '1592400876', '1878424319'],
      dtype='object', name='ISBN', length=731)

In [170]:
filtered_ratings = ratings[ratings['ISBN'].isin(valid_isbns)]

In [171]:
filtered_ratings

         User-ID        ISBN  Book-Rating
2         276727  0446520802            0
8         276744  038550120X            7
10        276746  0425115801            0
11        276746  0449006522            0
12        276746  0553561618            0
...          ...         ...          ...
1149749   276690  0064400557            0
1149761   276704  0345386108            6
1149768   276704  0446605409            0
1149771   276704  0743211383            7
1149772   276704  080410526X            0

[138461 rows x 3 columns]

In [172]:
avg_rating = filtered_ratings.groupby('ISBN')['Book-Rating'].mean()

In [173]:
result = avg_rating.sort_values(ascending=False)

In [174]:
result.head()

ISBN
0439064864    6.611765
0439139597    6.541237
0439136350    6.467005
0590353403    6.363095
043935806X    5.571856
Name: Book-Rating, dtype: float64

Har publisher ne kitne books publish kiye — sirf woh publishers rakho jinhone 50 se zyada books publish ki hain. Unhe sort karo descending mein.

In [176]:
books.head()

,ISBN,Book-Title,Book-Author,Year-Of-Publication,Publisher,Image-URL-S,Image-URL-M,Image-URL-L
0,0195153448,Classical Mythology,Mark P. O. Morford,2002.0,Oxford University Press,http://images.amazon.com/images/P/0195153448.0...,http://images.amazon.com/images/P/0195153448.0...,http://images.amazon.com/images/P/0195153448.0...
1,0002005018,Clara Callan,Richard Bruce Wright,2001.0,HarperFlamingo Canada,http://images.amazon.com/images/P/0002005018.0...,http://images.amazon.com/images/P/0002005018.0...,http://images.amazon.com/images/P/0002005018.0...
2,0060973129,Decision in Normandy,Carlo D'Este,1991.0,HarperPerennial,http://images.amazon.com/images/P/0060973129.0...,http://images.amazon.com/images/P/0060973129.0...,http://images.amazon.com/images/P/0060973129.0...
3,0374157065,Flu: The Story of the Great Influenza Pandemic...,Gina Bari Kolata,1999.0,Farrar Straus Giroux,http://images.amazon.com/images/P/0374157065.0...,http://images.amazon.com/images/P/0374157065.0...,http://images.amazon.com/images/P/0374157065.0...
4,0393045218,The Mummies of Urumchi,E. J. W. Barber,1999.0,W. W. Norton &amp; Company,http://images.amazon.com/images/P/0393045218.0...,http://images.amazon.com/images/P/0393045218.0...,http://images.amazon.com/images/P/0393045218.0...

In [177]:
publisher_counts = books.groupby('Publisher')['Book-Title'].count()

In [178]:
publisher_counts[publisher_counts > 50].sort_values(ascending=False)

Publisher
Harlequin                             7535
Silhouette                            4220
Pocket                                3905
Ballantine Books                      3783
Bantam Books                          3646
                                      ...
Everyman's Library                      51
Cornell University Press                51
Cook Communications Ministries (J)      51
W.W. Norton &amp; Company Ltd           51
Warner Forever                          51
Name: Book-Title, Length: 711, dtype: int64

groupby ke saath .agg() use karo — har ISBN ke liye ek saath count, mean, aur max rating ek hi DataFrame mein nikaal. Columns ka naam rakho: num_ratings, avg_rating, max_rating.

In [180]:
ratings

         User-ID         ISBN  Book-Rating
0         276725   034545104X            0
1         276726   0155061224            5
2         276727   0446520802            0
3         276729   052165615X            3
4         276729   0521795028            6
...          ...          ...          ...
1149775   276704   1563526298            9
1149776   276706   0679447156            0
1149777   276709   0515107662           10
1149778   276721   0590442449           10
1149779   276723  05162443314            8

[1149780 rows x 3 columns]

In [181]:
ratings.groupby('ISBN')['Book-Rating'].agg(['count', 'mean', 'max'])

             count  mean  max
ISBN
 0330299891      2   3.0    6
 0375404120      2   1.5    3
 0586045007      1   0.0    0
 9022906116      2   3.5    7
 9032803328      1   0.0    0
...            ...   ...  ...
cn113107         1   0.0    0
ooo7156103       1   7.0    7
§423350229       1   0.0    0
´3499128624      1   8.0    8
Ô½crosoft        1   7.0    7

[340556 rows x 3 columns]

In [182]:
ratings.groupby('ISBN')['Book-Rating'] .agg(num_ratings='count',avg_rating='mean',max_rating='max')

             num_ratings  avg_rating  max_rating
ISBN
 0330299891            2         3.0           6
 0375404120            2         1.5           3
 0586045007            1         0.0           0
 9022906116            2         3.5           7
 9032803328            1         0.0           0
...                  ...         ...         ...
cn113107               1         0.0           0
ooo7156103             1         7.0           7
§423350229             1         0.0           0
´3499128624            1         8.0           8
Ô½crosoft              1         7.0           7

[340556 rows x 3 columns]

2000 ke baad publish hue sabhi books nikaal jo "Stephen King" ne likhi hain.

In [184]:
books.head(2)

,ISBN,Book-Title,Book-Author,Year-Of-Publication,Publisher,Image-URL-S,Image-URL-M,Image-URL-L
0,0195153448,Classical Mythology,Mark P. O. Morford,2002.0,Oxford University Press,http://images.amazon.com/images/P/0195153448.0...,http://images.amazon.com/images/P/0195153448.0...,http://images.amazon.com/images/P/0195153448.0...
1,0002005018,Clara Callan,Richard Bruce Wright,2001.0,HarperFlamingo Canada,http://images.amazon.com/images/P/0002005018.0...,http://images.amazon.com/images/P/0002005018.0...,http://images.amazon.com/images/P/0002005018.0...

In [241]:
df=books[books['Book-Author']=='Stephen King']

In [247]:
df2=df[df['Year-Of-Publication']>=2000]

In [251]:
df2['Book-Title']

126                           The Girl Who Loved Tom Gordon
346                                        Mientras Escribo
502                                             The Shining
881                                            Dreamcatcher
925                                           The Dead Zone
                                ...
263349            LA Milla Verde: (El Pasillo De LA Muerte)
263562                   On Writing : A Memoir Of The Craft
266361                                  Los Ojos del Dragon
270899    Secret Windows: Essays and Fiction on the Craf...
271106               El Misterio De Salem's Lot/Salem's Lot
Name: Book-Title, Length: 169, dtype: object

In [253]:
books.head()

,ISBN,Book-Title,Book-Author,Year-Of-Publication,Publisher,Image-URL-S,Image-URL-M,Image-URL-L
0,0195153448,Classical Mythology,Mark P. O. Morford,2002.0,Oxford University Press,http://images.amazon.com/images/P/0195153448.0...,http://images.amazon.com/images/P/0195153448.0...,http://images.amazon.com/images/P/0195153448.0...
1,0002005018,Clara Callan,Richard Bruce Wright,2001.0,HarperFlamingo Canada,http://images.amazon.com/images/P/0002005018.0...,http://images.amazon.com/images/P/0002005018.0...,http://images.amazon.com/images/P/0002005018.0...
2,0060973129,Decision in Normandy,Carlo D'Este,1991.0,HarperPerennial,http://images.amazon.com/images/P/0060973129.0...,http://images.amazon.com/images/P/0060973129.0...,http://images.amazon.com/images/P/0060973129.0...
3,0374157065,Flu: The Story of the Great Influenza Pandemic...,Gina Bari Kolata,1999.0,Farrar Straus Giroux,http://images.amazon.com/images/P/0374157065.0...,http://images.amazon.com/images/P/0374157065.0...,http://images.amazon.com/images/P/0374157065.0...
4,0393045218,The Mummies of Urumchi,E. J. W. Barber,1999.0,W. W. Norton &amp; Company,http://images.amazon.com/images/P/0393045218.0...,http://images.amazon.com/images/P/0393045218.0...,http://images.amazon.com/images/P/0393045218.0...

In [255]:
df=books[books['Year-Of-Publication']>2000]

In [257]:
df2=df[df['Book-Author']=='Stephen King']

In [259]:
df2.loc[1:2]

Empty DataFrame
Columns: [ISBN, Book-Title, Book-Author, Year-Of-Publication, Publisher, Image-URL-S, Image-URL-M, Image-URL-L]
Index: []

In [261]:
df2[['Book-Title','Book-Author']]

                                       Book-Title   Book-Author
346                              Mientras Escribo  Stephen King
502                                   The Shining  Stephen King
881                                  Dreamcatcher  Stephen King
925                                 The Dead Zone  Stephen King
1651                                 Pet Sematary  Stephen King
...                                           ...           ...
259410                 La TempÃ?Âªte du siÃ?Â¨cle  Stephen King
263231                   From a Buick 8 : A Novel  Stephen King
263349  LA Milla Verde: (El Pasillo De LA Muerte)  Stephen King
266361                        Los Ojos del Dragon  Stephen King
271106     El Misterio De Salem's Lot/Salem's Lot  Stephen King

[121 rows x 2 columns]

Sirf woh ratings rakho jo 0 se zyada hain (explicit ratings). Percentage nikaal total ratings ka kitna % explicit hai.de

In [270]:
total_ratings = len(ratings)
ratings

         User-ID         ISBN  Book-Rating
0         276725   034545104X            0
1         276726   0155061224            5
2         276727   0446520802            0
3         276729   052165615X            3
4         276729   0521795028            6
...          ...          ...          ...
1149775   276704   1563526298            9
1149776   276706   0679447156            0
1149777   276709   0515107662           10
1149778   276721   0590442449           10
1149779   276723  05162443314            8

[1149780 rows x 3 columns]

In [268]:
total_ratings

1149780

In [272]:
explicit_count=len(ratings[ratings['Book-Rating']>0])

In [276]:
percentage = (explicit_count / total_ratings) * 100

In [278]:
percentage

37.71773730626728

Users jinka age 13 se 17 ke beech hai (inclusive) nikaal — teen readers. Unka count nikaal. Age ke nulls ko pehle drop karo.

In [282]:
users_clean=users.dropna(subset=['Age'])

In [284]:
users_clean[(users_clean['Age']<=17) & (users_clean['Age']>=13)].shape[0]

10844

Books jinka title mein "Harry Potter" word hai unhe nikaal. Book-Author bhi dekho — kitne alag authors listed hain? (hint: same book ke alag ISBNs hote hain)

In [287]:
books[['Book-Title','Book-Author']]

,Book-Title,Book-Author
0,Classical Mythology,Mark P. O. Morford
1,Clara Callan,Richard Bruce Wright
2,Decision in Normandy,Carlo D'Este
3,Flu: The Story of the Great Influenza Pandemic...,Gina Bari Kolata
4,The Mummies of Urumchi,E. J. W. Barber
...,...,...
271355,There's a Bat in Bunk Five,Paula Danziger
271356,From One to One Hundred,Teri Sloat
271357,Lily Dale : The True Story of the Town that Ta...,Christine Wicker
271358,Republic (World's Classics),Plato
271359,A Guided Tour of Rene Descartes' Meditations o...,Christopher Biffle

.str.contains() → string search
"Harry Potter" → keyword match
na=False → NaN values ko ignore

In [289]:
hp_books=books[books['Book-Title'].str.contains("Harry Potter", na=False)]

In [291]:
hp_books[['Book-Title', 'Book-Author']]

                                               Book-Title         Book-Author
821     The Sorcerer's Companion: A Guide to the Magic...  ALLAN ZOLA KRONZEK
2143    Harry Potter and the Sorcerer's Stone (Harry P...       J. K. Rowling
2809       Harry Potter and the Sorcerer's Stone (Book 1)       J. K. Rowling
3459     Harry Potter and the Chamber of Secrets (Book 2)       J. K. Rowling
3839    Harry Potter and the Prisoner of Azkaban (Book 3)       J. K. Rowling
...                                                   ...                 ...
247872                              Harry Potter Fun Book        Warner Bros.
251233                   Harry Potter y El Caliz de Fuego       J. K. Rowling
256403   Harry Potter and the Bible: The Menace Behind...      Richard Abanes
257263  Harry Potter and the Goblet of Fire (Harry Pot...       J. K. Rowling
259611              Harry Potter and the Sorcerer's Stone        J.K. Rowling

[120 rows x 2 columns]

In [293]:
hp_books['Book-Author'].nunique()

27

isin() use karke — woh users nikaal jinki User-ID in hain: [276725, 276726, 276727, 276729]. Unki saari ratings dikhao. Phir ~isin() se yeh users hatao aur remaining count print karo.

In [296]:
selected_users = [276725, 276726, 276727, 276729]

In [298]:
ratings['User-ID']

0          276725
1          276726
2          276727
3          276729
4          276729
            ...
1149775    276704
1149776    276706
1149777    276709
1149778    276721
1149779    276723
Name: User-ID, Length: 1149780, dtype: int64

In [300]:
ratings[ratings['User-ID'].isin(selected_users)]

   User-ID        ISBN  Book-Rating
0   276725  034545104X            0
1   276726  0155061224            5
2   276727  0446520802            0
3   276729  052165615X            3
4   276729  0521795028            6

In [302]:
#In users ko REMOVE karo
remaining = ratings[~ratings['User-ID'].isin(selected_users)]

In [304]:
remaining

         User-ID         ISBN  Book-Rating
5         276733   2080674722            0
6         276736   3257224281            8
7         276737   0600570967            6
8         276744   038550120X            7
9         276745    342310538           10
...          ...          ...          ...
1149775   276704   1563526298            9
1149776   276706   0679447156            0
1149777   276709   0515107662           10
1149778   276721   0590442449           10
1149779   276723  05162443314            8

[1149775 rows x 3 columns]

In [306]:
remaining.shape[0]

1149775

ratings aur books ko ISBN column pe merge karo (inner join). Naye DataFrame ka shape print karo aur samjhao kyun rows original ratings se kam hain.')

Inner join logic:
Sirf woh rows aayengi jinka ISBN dono tables me present hai
Agar ISBN match nahi hua → row drop ho jaati hai

In [308]:
merged_df=pd.merge(ratings,books,on='ISBN',how='inner')

In [310]:
merged_df.head()

,User-ID,ISBN,Book-Rating,Book-Title,Book-Author,Year-Of-Publication,Publisher,Image-URL-S,Image-URL-M,Image-URL-L
0,276725,034545104X,0,Flesh Tones: A Novel,M. J. Rose,2002.0,Ballantine Books,http://images.amazon.com/images/P/034545104X.0...,http://images.amazon.com/images/P/034545104X.0...,http://images.amazon.com/images/P/034545104X.0...
1,276726,0155061224,5,Rites of Passage,Judith Rae,2001.0,Heinle,http://images.amazon.com/images/P/0155061224.0...,http://images.amazon.com/images/P/0155061224.0...,http://images.amazon.com/images/P/0155061224.0...
2,276727,0446520802,0,The Notebook,Nicholas Sparks,1996.0,Warner Books,http://images.amazon.com/images/P/0446520802.0...,http://images.amazon.com/images/P/0446520802.0...,http://images.amazon.com/images/P/0446520802.0...
3,276729,052165615X,3,Help!: Level 1,Philip Prowse,1999.0,Cambridge University Press,http://images.amazon.com/images/P/052165615X.0...,http://images.amazon.com/images/P/052165615X.0...,http://images.amazon.com/images/P/052165615X.0...
4,276729,0521795028,6,The Amsterdam Connection : Level 4 (Cambridge ...,Sue Leather,2001.0,Cambridge University Press,http://images.amazon.com/images/P/0521795028.0...,http://images.amazon.com/images/P/0521795028.0...,http://images.amazon.com/images/P/0521795028.0...

You want to build a Collaborative Filtering Based Recommender System, and first step is:
“Find only those users who are active enough (have rated more than 200 books), so that recommendations become reliable.”

In [312]:
ratings_with_name = ratings.merge(books,on='ISBN')

In [314]:
ratings_with_name.groupby('User-ID')

In [316]:
#Count ratings per user
ratings_with_name.groupby('User-ID').count()['Book-Rating']

User-ID
2          1
8         17
9          3
10         1
12         1
          ..
278846     1
278849     4
278851    23
278852     1
278854     8
Name: Book-Rating, Length: 92106, dtype: int64

In [328]:
#filter
ratings_with_name.groupby('User-ID').count()['Book-Rating']>200

User-ID
2         False
8         False
9         False
10        False
12        False
          ...
278846    False
278849    False
278851    False
278852    False
278854    False
Name: Book-Rating, Length: 92106, dtype: bool

Keep only True users -> x[x] 👉 only True values remain 🧠 Why >200 threshold?
Get User IDs
.index 👉 final list of “active users”
Because:
low ratings users = noisy data
high ratings users = stable preferences
better similarity calculation

agar koi user sirf 2-3 books rate karta hai, uski preference reliable nahi hogi. Toh sirf woh users lo jinki "reading history" strong hai — 200+ books rate ki ho. x ek True/False Series hai. x[x] sirf True wale rakhta hai. .index se User-IDs milti hain.

| User | Likes                |
| ---- | -------------------- |
| A    | Harry Potter, LOTR   |
| B    | Harry Potter, Hobbit |
| C    | LOTR, Hobbit      

👉 If A and B are similar → recommend B’s books to A   |

In [322]:
x = ratings_with_name.groupby('User-ID').count()['Book-Rating'] > 200
active_users = x[x].index

In [324]:
x

User-ID
2         False
8         False
9         False
10        False
12        False
          ...
278846    False
278849    False
278851    False
278852    False
278854    False
Name: Book-Rating, Length: 92106, dtype: bool

In [330]:
filtered_rating = ratings_with_name[ratings_with_name['User-ID'].isin(active_users)]

Same logic books ke liye — agar kisi book ko sirf 3 logon ne rate kiya, uska similarity score noise hoga. Minimum 50 ratings wali books lo.

In [332]:
filtered_rating

,User-ID,ISBN,Book-Rating,Book-Title,Book-Author,Year-Of-Publication,Publisher,Image-URL-S,Image-URL-M,Image-URL-L
1150,277427,002542730X,10,Politically Correct Bedtime Stories: Modern Ta...,James Finn Garner,1994.0,John Wiley &amp; Sons Inc,http://images.amazon.com/images/P/002542730X.0...,http://images.amazon.com/images/P/002542730X.0...,http://images.amazon.com/images/P/002542730X.0...
1151,277427,0026217457,0,Vegetarian Times Complete Cookbook,Lucy Moll,1995.0,John Wiley &amp; Sons,http://images.amazon.com/images/P/0026217457.0...,http://images.amazon.com/images/P/0026217457.0...,http://images.amazon.com/images/P/0026217457.0...
1152,277427,003008685X,8,Pioneers,James Fenimore Cooper,1974.0,Thomson Learning,http://images.amazon.com/images/P/003008685X.0...,http://images.amazon.com/images/P/003008685X.0...,http://images.amazon.com/images/P/003008685X.0...
1153,277427,0030615321,0,"Ask for May, Settle for June (A Doonesbury book)",G. B. Trudeau,1982.0,Henry Holt &amp; Co,http://images.amazon.com/images/P/0030615321.0...,http://images.amazon.com/images/P/0030615321.0...,http://images.amazon.com/images/P/0030615321.0...
1154,277427,0060002050,0,On a Wicked Dawn (Cynster Novels),Stephanie Laurens,2002.0,Avon Books,http://images.amazon.com/images/P/0060002050.0...,http://images.amazon.com/images/P/0060002050.0...,http://images.amazon.com/images/P/0060002050.0...
...,...,...,...,...,...,...,...,...,...,...
1029357,275970,1931868123,0,There's a Porcupine in My Outhouse: Misadventu...,Mike Tougias,2002.0,Capital Books (VA),http://images.amazon.com/images/P/1931868123.0...,http://images.amazon.com/images/P/1931868123.0...,http://images.amazon.com/images/P/1931868123.0...
1029358,275970,3411086211,10,Die Biene.,Sybil GrÃ?Â¤fin SchÃ?Â¶nfeldt,1993.0,"Bibliographisches Institut, Mannheim",http://images.amazon.com/images/P/3411086211.0...,http://images.amazon.com/images/P/3411086211.0...,http://images.amazon.com/images/P/3411086211.0...
1029359,275970,3829021860,0,The Penis Book,Joseph Cohen,1999.0,Konemann,http://images.amazon.com/images/P/3829021860.0...,http://images.amazon.com/images/P/3829021860.0...,http://images.amazon.com/images/P/3829021860.0...
1029360,275970,4770019572,0,Musashi,Eiji Yoshikawa,1995.0,Kodansha International (JPN),http://images.amazon.com/images/P/4770019572.0...,http://images.amazon.com/images/P/4770019572.0...,http://images.amazon.com/images/P/4770019572.0...
1029361,275970,9626340762,8,Northanger Abbey (Classic Literature with Clas...,Jane Austen,1996.0,Naxos Audiobooks Ltd.,http://images.amazon.com/images/P/9626340762.0...,http://images.amazon.com/images/P/9626340762.0...,http://images.amazon.com/images/P/9626340762.0...

In [334]:
filtered_rating.groupby('Book-Title').count()['Book-Rating'] >= 50

Book-Title
 A Light in the Storm: The Civil War Diary of Amelia Martin, Fenwick Island, Delaware, 1861 (Dear America)    False
 Always Have Popsicles                                                                                        False
 Apple Magic (The Collector's series)                                                                         False
 Beyond IBM: Leadership Marketing and Finance for the 1990s                                                   False
 Clifford Visita El Hospital (Clifford El Gran Perro Colorado)                                                False
                                                                                                              ...
Ã?Â?ber das Fernsehen.                                                                                        False
Ã?Â?ber die Pflicht zum Ungehorsam gegen den Staat.                                                           False
Ã?Â?lpiraten.                                                                                                 False
Ã?Â?stlich der Berge.                                                                                         False
Ã?Â?thique en toc                                                                                             False
Name: Book-Rating, Length: 155845, dtype: bool

| Book | Ratings |
| ---- | ------- |
| A    | 2       |
| B    | 10      |
| C    | 500  

“Books jinko enough logon ne rate kiya hai”   |

In [336]:
y = filtered_rating.groupby('Book-Title').count()['Book-Rating'] >= 50
famous_books = y[y].index
#Keep only True books y[y] 👉 only popular books remain

# FINAL STEP: Pivot Table (CORE IDEA)

BEFORE:

User1 → BookA → 5
User2 → BookA → 0
User3 → BookA 4 →

AFTER:

            User1  User2  User3
BookA         5      0      4
BookB         0      3     0 4

In [338]:
final_ratings = filtered_rating[filtered_rating['Book-Title'].isin(famous_books)]

In [342]:
pt = final_ratings.pivot_table(
    index='Book-Title',
    columns='User-ID',
    values='Book-Rating'
)

WHY pivot table?

Because collaborative filtering needs:

“Item-user matrix”

So we can compare:

Book vs Book similarity
User pattern similarity

In [344]:
pt.head()

User-ID,254,2276,2766,2977,3363,4017,4385,6251,6323,6543,...,271705,273979,274004,274061,274301,274308,275970,277427,277639,278418
Book-Title,,,,,,,,,,,,,,,,,,,,,
1984,9.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,10.0,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN
1st to Die: A Novel,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2nd Chance,NaN,10.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,...,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,0.0,NaN
4 Blondes,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
A Bend in the Road,0.0,NaN,7.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [351]:
pt.fillna(0, inplace=True)

# working

Users ka kaam tha:
“Books ko compare karne ke liye behavior provide karna”

| Book \ User | U1 | U2 | U3 | U4 |
| ----------- | -- | -- | -- | -- |
| Book A      | 5  | 0  | 3  | 0  |
| Book B      | 0  | 4  | 0  | 2  |
| Book C      | 1  | 1  | 0  | 5  |

cosine_similarity(pt) kya karta hai?
cosine_similarity(pt)

👉 Har row (book) ko ek vector maanta hai

Book A = [5, 0, 3, 0]
Book B = [0, 4, 0, 2]
Book C = [1, 1, 05], 

Step 2: Pairwise comparison

Cosine similarity har pair compare karta hai:

Book A vs Book B
Book A vs Book C
Book B vs Book C

Step 3: Formula behind scenes

cos(θ)=A⋅B/∥A∥∥B∥

If two books:
same users rate same way → similarity HIGH (≈1)
different users → similarity LOW (≈0)
📊 4. Output: similarity_scores
similarity_scores = cosine_similarity(pt)


Why this is used in recommendation system?

When user likes Book A: 👉 system checks:
similarity_scores[A] → top similar books 👉 and recommends them5]

In [355]:
from sklearn.metrics.pairwise import cosine_similarity
similarity_scores = cosine_similarity(pt)
similarity_scores.shape

(706, 706)

Output: similarity_scores
|   | A   | B   | C   |
| - | --- | --- | --- |
| A | 1.0 | 0.2 | 0.8 |
| B | 0.2 | 1.0 | 0.1 |
| C | 0.8 | 0.1 | 1.0 |

| Book \ User | U1 | U2 | U3 |
| ----------- | -- | -- | -- |
| A           | 5  | 0  | 3  |
| B           | 5  | 0  | 2  |
| C           | 0  | 4  | 0“Kaun si books same users ne same tarah rate ki?”

👉 isse banta hai:

Book A ≈ Book B
Book A ≠ Book C

✅ STEP 1: User ne ek book padhi

Example: 👉 User X liked:
Book A
✅ STEP 2: system check karega similarity
similarity_scores['Book A']

👉 output:

Book B → 0.9
Book C → 0.2
Book D → 0.8

✅ STEP 3: top similar books pick

👉 system selects:

Book B
Book D
🎯 FINAL RESULT: “User X ko Book B aur Book D recommend karo”  |

In [373]:
book_name = "The Shining"

In [375]:
import numpy as np

In [377]:
np.where(pt.index == "A Bend in the Road") #ye tuple hai

(array([4]),)

In [379]:
np.where(pt.index == "A Bend in the Road")[0]

array([4])

In [381]:
np.where(pt.index == "A Bend in the Road")[0][0]

np.int64(4)

In [383]:
x = np.int64(4)
print(x)

4

In [385]:
book_name = "A Bend in the Road"

In [391]:
# kis row pe hai similarity matrix me?
index = np.where(pt.index == book_name)[0][0]

In [393]:
#Us book ki similarity row lo
similarity_scores[index]
#har book se kitni similar hai

array([0.05367224, 0.1095379 , 0.06909024, 0.        , 1.        ,
       0.1013312 , 0.09627016, 0.03993342, 0.07452159, 0.        ,
       0.0530616 , 0.00616629, 0.03418429, 0.04942968, 0.1289979 ,
       0.08192427, 0.19985266, 0.08880666, 0.10177542, 0.13586621,
       0.        , 0.        , 0.03229365, 0.10584252, 0.29562612,
       0.12047151, 0.07456711, 0.10458247, 0.03601541, 0.04888169,
       0.01754798, 0.03365952, 0.05223377, 0.18909339, 0.        ,
       0.16137408, 0.08068053, 0.0416527 , 0.05964277, 0.12075564,
       0.        , 0.10738992, 0.03951803, 0.25099279, 0.03148457,
       0.09572116, 0.        , 0.0908854 , 0.0648952 , 0.06310897,
       0.01245924, 0.        , 0.09978939, 0.        , 0.1620452 ,
       0.04975287, 0.0657618 , 0.20838265, 0.04113637, 0.06087709,
       0.0406275 , 0.10310093, 0.1068425 , 0.1584111 , 0.08301227,
       0.04749344, 0.086492  , 0.        , 0.1660846 , 0.08418528,
       0.        , 0.07096117, 0.        , 0.08642273, 0.1077389 ,
       0.11167735, 0.20851525, 0.1524991 , 0.03042444, 0.22741184,
       0.02733105, 0.10016465, 0.02115206, 0.04808603, 0.03379518,
       0.05620666, 0.1124018 , 0.13977297, 0.09868857, 0.23649512,
       0.09372499, 0.        , 0.05600299, 0.03843687, 0.0725149 ,
       0.10725909, 0.04831938, 0.0614092 , 0.06883229, 0.03899905,
       0.0365941 , 0.04500512, 0.11303574, 0.12398783, 0.12163511,
       0.06189027, 0.17035497, 0.06178409, 0.06420188, 0.23486335,
       0.04835332, 0.04793117, 0.        , 0.06541566, 0.08532576,
       0.        , 0.07384882, 0.15506947, 0.11100902, 0.06123002,
       0.13752414, 0.02466412, 0.14246499, 0.2393642 , 0.19887337,
       0.07425933, 0.21988255, 0.03931659, 0.        , 0.07253635,
       0.21607888, 0.        , 0.048693  , 0.        , 0.07184502,
       0.11381607, 0.1006452 , 0.11256797, 0.        , 0.03861585,
       0.05508233, 0.17586632, 0.        , 0.        , 0.08602579,
       0.02410985, 0.05934247, 0.01956782, 0.04861211, 0.04991641,
       0.12156431, 0.09868516, 0.07865689, 0.08249585, 0.05867054,
       0.08591989, 0.0322436 , 0.        , 0.08364555, 0.02015709,
       0.15708078, 0.        , 0.0936225 , 0.12083357, 0.05452543,
       0.06778172, 0.08375685, 0.06094551, 0.10756591, 0.08985142,
       0.03758907, 0.14047378, 0.19960225, 0.        , 0.06352409,
       0.12810145, 0.        , 0.07311029, 0.05220674, 0.        ,
       0.19112134, 0.03981448, 0.08943781, 0.076711  , 0.0500367 ,
       0.04600469, 0.24631687, 0.08951447, 0.12620945, 0.15266909,
       0.06883292, 0.        , 0.20241005, 0.1710158 , 0.15818234,
       0.0254448 , 0.14654601, 0.10102909, 0.10730208, 0.09881641,
       0.11318059, 0.06175405, 0.06802151, 0.12031482, 0.05521018,
       0.06483801, 0.10556941, 0.03974998, 0.12458997, 0.13003278,
       0.06998316, 0.02914592, 0.17480442, 0.06851138, 0.12597532,
       0.0444749 , 0.05204275, 0.03797193, 0.22380463, 0.0570722 ,
       0.16253529, 0.05323082, 0.        , 0.13861809, 0.        ,
       0.08263509, 0.12964036, 0.04658407, 0.10609849, 0.06431051,
       0.0388389 , 0.060984  , 0.04221607, 0.15318782, 0.1144481 ,
       0.09649772, 0.10824441, 0.0559269 , 0.07652002, 0.04878797,
       0.13982858, 0.07085211, 0.0464289 , 0.09701786, 0.03414003,
       0.01411072, 0.11206382, 0.04662722, 0.        , 0.06669269,
       0.06068668, 0.19519399, 0.03200283, 0.1380974 , 0.04915208,
       0.        , 0.07581577, 0.1003865 , 0.10643367, 0.09843704,
       0.09299889, 0.07519316, 0.09275266, 0.16842124, 0.        ,
       0.17205355, 0.07361258, 0.10022399, 0.05571168, 0.01808441,
       0.10092097, 0.        , 0.1325831 , 0.        , 0.13484632,
       0.06993711, 0.12795938, 0.15726583, 0.11093802, 0.09424953,
       0.10395467, 0.        , 0.02024291, 0.06581554, 0.14286796,
       0.0551568 , 0.08931043, 0.        , 0.05671949, 0.15827619,
       0.06030181, 0.15270967, 0.10143157, 0.02786683, 0.08849141,
       0.02880676, 0.05425808, 0.05304942, 0.20302008, 0.16334072,
       0.16346593, 0.04857805, 0.1446107 , 0.22301781, 0.09471874,
       0.05525074, 0.05634957, 0.06145395, 0.        , 0.0637988 ,
       0.09892244, 0.05968092, 0.1099974 , 0.0238161 , 0.1315398 ,
       0.        , 0.        , 0.04619853, 0.07279216, 0.11379857,
       0.14901356, 0.06977747, 0.11515388, 0.0195262 , 0.09779397,
       0.14576495, 0.13284089, 0.0769061 , 0.14721505, 0.06094551,
       0.15264424, 0.06989225, 0.04185622, 0.04975015, 0.08959386,
       0.15011024, 0.        , 0.02429269, 0.15041654, 0.06731903,
       0.06136364, 0.09854884, 0.10569548, 0.06871961, 0.08484641,
       0.03551179, 0.05879094, 0.03035566, 0.05360112, 0.08709472,
       0.04487708, 0.        , 0.15472949, 0.11976421, 0.05390584,
       0.23652296, 0.14347518, 0.        , 0.03863751, 0.06716586,
       0.        , 0.04129099, 0.14938829, 0.07854441, 0.00551353,
       0.15020573, 0.04558276, 0.        , 0.1078395 , 0.        ,
       0.04106059, 0.        , 0.04950754, 0.12132955, 0.08525861,
       0.04064297, 0.09902962, 0.08594319, 0.        , 0.13198505,
       0.12463923, 0.10982696, 0.04014971, 0.05646305, 0.04116172,
       0.13738308, 0.01847266, 0.        , 0.0492523 , 0.09103608,
       0.        , 0.04782079, 0.02720034, 0.14815553, 0.11301544,
       0.05249185, 0.11601388, 0.0555938 , 0.04388675, 0.07614992,
       0.08978406, 0.03532111, 0.        , 0.13614592, 0.09890758,
       0.12005958, 0.06325285, 0.0434925 , 0.        , 0.05316272,
       0.09199732, 0.05321278, 0.04540429, 0.19315673, 0.11394486,
       0.09133847, 0.19058762, 0.04347654, 0.2604335 , 0.15252894,
       0.0370853 , 0.13729848, 0.06795495, 0.04125594, 0.06587008,
       0.1315398 , 0.0551457 , 0.15284949, 0.0343785 , 0.09867018,
       0.09035727, 0.00371686, 0.04817884, 0.05964775, 0.1093814 ,
       0.09583111, 0.09623985, 0.04004311, 0.06624887, 0.05071691,
       0.15885388, 0.04836698, 0.        , 0.18812758, 0.13591049,
       0.0525656 , 0.11747551, 0.08148164, 0.13283777, 0.        ,
       0.09758141, 0.08711968, 0.02132387, 0.        , 0.08680457,
       0.05460733, 0.11039364, 0.06394134, 0.02962734, 0.0546488 ,
       0.03927054, 0.06125578, 0.19067415, 0.14766333, 0.12839621,
       0.        , 0.11214013, 0.0802352 , 0.03773155, 0.04279679,
       0.17654166, 0.        , 0.10953853, 0.        , 0.08715301,
       0.        , 0.08744261, 0.        , 0.04020861, 0.04551348,
       0.04796382, 0.18594225, 0.        , 0.08078489, 0.05440313,
       0.        , 0.21093948, 0.02436595, 0.07549606, 0.04182672,
       0.09341994, 0.05907026, 0.        , 0.        , 0.11215608,
       0.09481725, 0.06406325, 0.10906973, 0.        , 0.11613162,
       0.05181828, 0.09457349, 0.072715  , 0.15241965, 0.14167447,
       0.14572896, 0.04633043, 0.01314877, 0.03716303, 0.05556092,
       0.13941028, 0.03293401, 0.11876917, 0.03243846, 0.08786235,
       0.04210111, 0.03841177, 0.03226837, 0.17428491, 0.        ,
       0.        , 0.09241445, 0.00472352, 0.06827022, 0.13966429,
       0.        , 0.05125148, 0.04542209, 0.01161988, 0.07995234,
       0.20255368, 0.04950934, 0.04981154, 0.21203793, 0.15137551,
       0.04739015, 0.11864291, 0.07860441, 0.08222798, 0.05562404,
       0.05506633, 0.05719858, 0.0612013 , 0.15155963, 0.04962179,
       0.0275457 , 0.01859585, 0.0419947 , 0.05950951, 0.10524825,
       0.04278546, 0.02881946, 0.19919062, 0.1892838 , 0.03679817,
       0.03444621, 0.19607207, 0.15535643, 0.04932036, 0.05648097,
       0.02347945, 0.05399853, 0.08668098, 0.06620459, 0.29142142,
       0.        , 0.07818196, 0.10472207, 0.09769847, 0.0523246 ,
       0.16642323, 0.04190874, 0.        , 0.13232387, 0.        ,
       0.13187829, 0.0897049 , 0.17175825, 0.08534322, 0.16950586,
       0.00524003, 0.16262194, 0.10170784, 0.04991325, 0.09746313,
       0.        , 0.05417885, 0.15200825, 0.0980474 , 0.11608854,
       0.05956719, 0.        , 0.00733172, 0.0696036 , 0.        ,
       0.13916195, 0.09254706, 0.10208923, 0.14183201, 0.05698494,
       0.0389557 , 0.14406291, 0.23600181, 0.11386274, 0.093071  ,
       0.020979  , 0.06480132, 0.05270152, 0.        , 0.04776897,
       0.11461583, 0.06561303, 0.06623312, 0.21317315, 0.080903  ,
       0.07845644, 0.05584337, 0.        , 0.03688226, 0.09892164,
       0.13680925, 0.179395  , 0.0893163 , 0.17940862, 0.0278069 ,
       0.0381894 , 0.04773196, 0.05656349, 0.05306261, 0.02394712,
       0.05586875, 0.01740343, 0.10628029, 0.11301407, 0.02763578,
       0.02453009, 0.04183776, 0.07950779, 0.04656118, 0.        ,
       0.03576488, 0.09880878, 0.18445486, 0.04166259, 0.13041992,
       0.08437235, 0.02930724, 0.13694941, 0.06397227, 0.05022244,
       0.08165008, 0.18059392, 0.08765034, 0.12555832, 0.192599  ,
       0.09538187, 0.06871818, 0.09638292, 0.11753286, 0.07182198,
       0.10096148, 0.071663  , 0.13497285, 0.16976925, 0.10306261,
       0.15060356, 0.15118216, 0.        , 0.02423639, 0.        ,
       0.03988115, 0.13842363, 0.11601311, 0.07504976, 0.07734068,
       0.0453357 , 0.08357781, 0.02953172, 0.04722587, 0.        ,
       0.07823385, 0.10075353, 0.05058548, 0.09848327, 0.        ,
       0.11941327, 0.06679359, 0.        , 0.1930344 , 0.13202584,
       0.0628892 , 0.        , 0.07339129, 0.05500764, 0.07759105,
       0.08532576, 0.07638746, 0.08215798, 0.022133  , 0.07581577,
       0.02558661, 0.        , 0.09848835, 0.04001749, 0.11284126,
       0.01520436])

In [395]:
# Har similarity ko book index ke saath pair karo
list(enumerate(similarity_scores[index]))

[(0, np.float64(0.053672244225442485)),
 (1, np.float64(0.10953789733294741)),
 (2, np.float64(0.06909024214591328)),
 (3, np.float64(0.0)),
 (4, np.float64(1.0)),
 (5, np.float64(0.10133120190422104)),
 (6, np.float64(0.09627015869844611)),
 (7, np.float64(0.039933422958493336)),
 (8, np.float64(0.07452158863876493)),
 (9, np.float64(0.0)),
 (10, np.float64(0.053061604331357225)),
 (11, np.float64(0.006166291672978489)),
 (12, np.float64(0.034184285395816506)),
 (13, np.float64(0.049429679670861135)),
 (14, np.float64(0.12899789835797454)),
 (15, np.float64(0.08192426594036471)),
 (16, np.float64(0.1998526607378485)),
 (17, np.float64(0.08880666054569399)),
 (18, np.float64(0.10177541679374065)),
 (19, np.float64(0.13586621177840782)),
 (20, np.float64(0.0)),
 (21, np.float64(0.0)),
 (22, np.float64(0.032293651665519715)),
 (23, np.float64(0.10584251806170297)),
 (24, np.float64(0.2956261183177974)),
 (25, np.float64(0.12047151286571994)),
 (26, np.float64(0.07456711015965088)),
 (27, np.float64(0.1045824704145169)),
 (28, np.float64(0.036015407710630366)),
 (29, np.float64(0.04888168510935883)),
 (30, np.float64(0.01754797834543235)),
 (31, np.float64(0.0336595173635295)),
 (32, np.float64(0.052233774851865415)),
 (33, np.float64(0.1890933926907012)),
 (34, np.float64(0.0)),
 (35, np.float64(0.16137407595941608)),
 (36, np.float64(0.08068052773761876)),
 (37, np.float64(0.04165270177329706)),
 (38, np.float64(0.05964277420389812)),
 (39, np.float64(0.12075564416754958)),
 (40, np.float64(0.0)),
 (41, np.float64(0.10738992353324073)),
 (42, np.float64(0.039518033611337294)),
 (43, np.float64(0.25099279007642467)),
 (44, np.float64(0.0314845704272096)),
 (45, np.float64(0.0957211606580172)),
 (46, np.float64(0.0)),
 (47, np.float64(0.09088540267181502)),
 (48, np.float64(0.06489519889620754)),
 (49, np.float64(0.06310897210025504)),
 (50, np.float64(0.01245924260561017)),
 (51, np.float64(0.0)),
 (52, np.float64(0.09978939402382297)),
 (53, np.float64(0.0)),
 (54, np.float64(0.1620452031141308)),
 (55, np.float64(0.04975287072286606)),
 (56, np.float64(0.06576179954638957)),
 (57, np.float64(0.2083826514146727)),
 (58, np.float64(0.04113636656377598)),
 (59, np.float64(0.060877092727929565)),
 (60, np.float64(0.04062750304948003)),
 (61, np.float64(0.10310092811484417)),
 (62, np.float64(0.10684249563248954)),
 (63, np.float64(0.1584111045028254)),
 (64, np.float64(0.08301226954650814)),
 (65, np.float64(0.04749343695357171)),
 (66, np.float64(0.08649199743313662)),
 (67, np.float64(0.0)),
 (68, np.float64(0.1660845973761384)),
 (69, np.float64(0.08418528345320406)),
 (70, np.float64(0.0)),
 (71, np.float64(0.07096116825953555)),
 (72, np.float64(0.0)),
 (73, np.float64(0.08642273331352725)),
 (74, np.float64(0.10773889516608476)),
 (75, np.float64(0.11167735342516456)),
 (76, np.float64(0.20851524976159672)),
 (77, np.float64(0.15249909639418213)),
 (78, np.float64(0.030424435999275367)),
 (79, np.float64(0.2274118409096433)),
 (80, np.float64(0.027331047436399702)),
 (81, np.float64(0.10016465338348816)),
 (82, np.float64(0.021152055507844943)),
 (83, np.float64(0.04808603356272168)),
 (84, np.float64(0.03379518359174745)),
 (85, np.float64(0.05620666394498556)),
 (86, np.float64(0.11240180335559083)),
 (87, np.float64(0.13977297055473362)),
 (88, np.float64(0.09868857036943512)),
 (89, np.float64(0.23649511822178387)),
 (90, np.float64(0.09372499124790423)),
 (91, np.float64(0.0)),
 (92, np.float64(0.05600298808398206)),
 (93, np.float64(0.038436870340119826)),
 (94, np.float64(0.07251489607581468)),
 (95, np.float64(0.10725908729725687)),
 (96, np.float64(0.048319376555266434)),
 (97, np.float64(0.061409201527523154)),
 (98, np.float64(0.06883229313632551)),
 (99, np.float64(0.03899905280708436)),
 (100, np.float64(0.03659409749250647)),
 (101, np.float64(0.04500511725125633)),
 (102, np.float64(0.11303573712327719)),
 (103, np.float64(0.12398783061125455)),
 (104, np.float64(0.12163510741352704)),
 (105, np.float64(0.06189027076728807)),
 (106, np.float64(0.17035497355630025)),
 (107, np.float64(0.06178409028739132)),
 (108, np.float64(0.06420187745962846)),
 (109, np.float64(0.2348633548353731)),
 (110, np.float64(0.04835332126895767)),
 (111, np.float64(0.04793117373659609)),
 (112, np.float64(0.0)),
 (113, np.float64(0.06541566235808073)),
 (114, np.float64(0.08532575676944276)),
 (115, np.float64(0.0)),
 (116, np.float64(0.07384881569561703)),
 (117, np.float64(0.15506947210744573)),
 (118, np.float64(0.11100902485079127)),
 (119, np.float64(0.061230017217087616)),
 (120, np.float64(0.13752413559379936)),
 (121, np.float64(0.02466412383346088)),
 (122, np.float64(0.14246498929097187)),
 (123, np.float64(0.2393641964122777)),
 (124, np.float64(0.1988733693429147)),
 (125, np.float64(0.07425933272822495)),
 (126, np.float64(0.219882553755762)),
 (127, np.float64(0.03931658734716883)),
 (128, np.float64(0.0)),
 (129, np.float64(0.07253634691272245)),
 (130, np.float64(0.21607888123802085)),
 (131, np.float64(0.0)),
 (132, np.float64(0.04869300418241175)),
 (133, np.float64(0.0)),
 (134, np.float64(0.07184502455215111)),
 (135, np.float64(0.11381607388381307)),
 (136, np.float64(0.10064519545287037)),
 (137, np.float64(0.11256796652108404)),
 (138, np.float64(0.0)),
 (139, np.float64(0.03861585330323392)),
 (140, np.float64(0.055082328304783004)),
 (141, np.float64(0.17586631904766403)),
 (142, np.float64(0.0)),
 (143, np.float64(0.0)),
 (144, np.float64(0.08602578963521729)),
 (145, np.float64(0.024109848378963405)),
 (146, np.float64(0.05934247162898372)),
 (147, np.float64(0.019567819737891762)),
 (148, np.float64(0.048612111339779614)),
 (149, np.float64(0.0499164099101778)),
 (150, np.float64(0.12156431347005998)),
 (151, np.float64(0.0986851612746874)),
 (152, np.float64(0.07865688992891055)),
 (153, np.float64(0.08249584588850199)),
 (154, np.float64(0.058670543456002276)),
 (155, np.float64(0.08591988910703714)),
 (156, np.float64(0.032243600806479034)),
 (157, np.float64(0.0)),
 (158, np.float64(0.08364554682635997)),
 (159, np.float64(0.02015708998312375)),
 (160, np.float64(0.15708078102990347)),
 (161, np.float64(0.0)),
 (162, np.float64(0.09362249640618785)),
 (163, np.float64(0.12083356575073129)),
 (164, np.float64(0.05452543051594516)),
 (165, np.float64(0.06778171714330687)),
 (166, np.float64(0.0837568479186244)),
 (167, np.float64(0.06094550929590378)),
 (168, np.float64(0.10756591328801518)),
 (169, np.float64(0.08985142249524665)),
 (170, np.float64(0.0375890698798613)),
 (171, np.float64(0.14047377789633286)),
 (172, np.float64(0.19960225461925957)),
 (173, np.float64(0.0)),
 (174, np.float64(0.06352409044202724)),
 (175, np.float64(0.1281014501916285)),
 (176, np.float64(0.0)),
 (177, np.float64(0.07311029374421943)),
 (178, np.float64(0.052206735640094246)),
 (179, np.float64(0.0)),
 (180, np.float64(0.1911213365753845)),
 (181, np.float64(0.03981448164919326)),
 (182, np.float64(0.0894378088601954)),
 (183, np.float64(0.07671099868036438)),
 (184, np.float64(0.05003669807337691)),
 (185, np.float64(0.04600468891290407)),
 (186, np.float64(0.24631687323985013)),
 (187, np.float64(0.08951447494265241)),
 (188, np.float64(0.12620945301905148)),
 (189, np.float64(0.15266909239224685)),
 (190, np.float64(0.0688329213320721)),
 (191, np.float64(0.0)),
 (192, np.float64(0.2024100521184496)),
 (193, np.float64(0.17101580258902152)),
 (194, np.float64(0.1581823408370724)),
 (195, np.float64(0.025444797479770694)),
 (196, np.float64(0.14654601452273808)),
 (197, np.float64(0.10102909295231167)),
 (198, np.float64(0.10730207900031254)),
 (199, np.float64(0.0988164092485403)),
 (200, np.float64(0.11318058624426793)),
 (201, np.float64(0.06175405238722145)),
 (202, np.float64(0.06802151324341349)),
 (203, np.float64(0.12031481637649427)),
 (204, np.float64(0.0552101837692816)),
 (205, np.float64(0.06483801478716504)),
 (206, np.float64(0.10556940608795268)),
 (207, np.float64(0.0397499784884159)),
 (208, np.float64(0.12458997146053968)),
 (209, np.float64(0.13003278212307726)),
 (210, np.float64(0.06998316485710616)),
 (211, np.float64(0.029145923326930348)),
 (212, np.float64(0.17480442244030567)),
 (213, np.float64(0.06851137773243196)),
 (214, np.float64(0.12597531639808796)),
 (215, np.float64(0.04447489943329245)),
 (216, np.float64(0.05204274577943038)),
 (217, np.float64(0.03797193099116368)),
 (218, np.float64(0.223804634455265)),
 (219, np.float64(0.05707219508177652)),
 (220, np.float64(0.16253528818433313)),
 (221, np.float64(0.053230816665893764)),
 (222, np.float64(0.0)),
 (223, np.float64(0.1386180932186325)),
 (224, np.float64(0.0)),
 (225, np.float64(0.08263509233569742)),
 (226, np.float64(0.12964035741312666)),
 (227, np.float64(0.04658407029015853)),
 (228, np.float64(0.10609849134164244)),
 (229, np.float64(0.0643105075031297)),
 (230, np.float64(0.0388388973424461)),
 (231, np.float64(0.06098399656223388)),
 (232, np.float64(0.04221607195068862)),
 (233, np.float64(0.1531878154902646)),
 (234, np.float64(0.11444809649006472)),
 (235, np.float64(0.09649772410582316)),
 (236, np.float64(0.10824441317156676)),
 (237, np.float64(0.055926895399998025)),
 (238, np.float64(0.07652002200483533)),
 (239, np.float64(0.04878796914661301)),
 (240, np.float64(0.13982858209651566)),
 (241, np.float64(0.07085210672611977)),
 (242, np.float64(0.046428903789937574)),
 (243, np.float64(0.09701786344012503)),
 (244, np.float64(0.034140026402103826)),
 (245, np.float64(0.01411071880225081)),
 (246, np.float64(0.11206382099155054)),
 (247, np.float64(0.04662722255344585)),
 (248, np.float64(0.0)),
 (249, np.float64(0.06669268937925227)),
 (250, np.float64(0.060686682791002755)),
 (251, np.float64(0.1951939916990976)),
 (252, np.float64(0.03200282586120489)),
 (253, np.float64(0.13809739584346814)),
 (254, np.float64(0.04915207535382561)),
 (255, np.float64(0.0)),
 (256, np.float64(0.07581577231588457)),
 (257, np.float64(0.10038650015908712)),
 (258, np.float64(0.10643366596593369)),
 (259, np.float64(0.09843704256463291)),
 (260, np.float64(0.09299888676478058)),
 (261, np.float64(0.07519315753538473)),
 (262, np.float64(0.09275265701169177)),
 (263, np.float64(0.1684212360665015)),
 (264, np.float64(0.0)),
 (265, np.float64(0.17205354536752948)),
 (266, np.float64(0.07361257841674783)),
 (267, np.float64(0.10022399061209131)),
 (268, np.float64(0.055711682560441275)),
 (269, np.float64(0.018084413988560585)),
 (270, np.float64(0.100920965229851)),
 (271, np.float64(0.0)),
 (272, np.float64(0.13258309898021106)),
 (273, np.float64(0.0)),
 (274, np.float64(0.13484631742538605)),
 (275, np.float64(0.06993710518875186)),
 (276, np.float64(0.1279593836402801)),
 (277, np.float64(0.15726582741740391)),
 (278, np.float64(0.11093802171695126)),
 (279, np.float64(0.09424952674957685)),
 (280, np.float64(0.10395466901518853)),
 (281, np.float64(0.0)),
 (282, np.float64(0.020242906451564728)),
 (283, np.float64(0.0658155382233493)),
 (284, np.float64(0.14286795949485578)),
 (285, np.float64(0.05515680126275032)),
 (286, np.float64(0.08931042616302126)),
 (287, np.float64(0.0)),
 (288, np.float64(0.05671949472094458)),
 (289, np.float64(0.1582761860008212)),
 (290, np.float64(0.060301806375061856)),
 (291, np.float64(0.15270966651225365)),
 (292, np.float64(0.10143156943262387)),
 (293, np.float64(0.027866830469835076)),
 (294, np.float64(0.08849141445161834)),
 (295, np.float64(0.028806755577457713)),
 (296, np.float64(0.05425808452511214)),
 (297, np.float64(0.05304942477112598)),
 (298, np.float64(0.20302007505751696)),
 (299, np.float64(0.1633407175015672)),
 (300, np.float64(0.16346593194669062)),
 (301, np.float64(0.04857804744295661)),
 (302, np.float64(0.1446107039218946)),
 (303, np.float64(0.22301781035065882)),
 (304, np.float64(0.09471874201875989)),
 (305, np.float64(0.05525073939796752)),
 (306, np.float64(0.056349571182220386)),
 (307, np.float64(0.0614539503578297)),
 (308, np.float64(0.0)),
 (309, np.float64(0.06379879883035562)),
 (310, np.float64(0.09892243604377954)),
 (311, np.float64(0.05968091725553759)),
 (312, np.float64(0.10999739643366067)),
 (313, np.float64(0.023816102754610283)),
 (314, np.float64(0.13153979683766578)),
 (315, np.float64(0.0)),
 (316, np.float64(0.0)),
 (317, np.float64(0.046198528246699906)),
 (318, np.float64(0.07279215995387318)),
 (319, np.float64(0.11379856745533079)),
 (320, np.float64(0.14901356420795267)),
 (321, np.float64(0.06977747216769732)),
 (322, np.float64(0.11515387663800894)),
 (323, np.float64(0.019526198682511854)),
 (324, np.float64(0.0977939717014365)),
 (325, np.float64(0.1457649460829311)),
 (326, np.float64(0.13284088899542693)),
 (327, np.float64(0.07690609569706935)),
 (328, np.float64(0.1472150517919098)),
 (329, np.float64(0.06094550929590378)),
 (330, np.float64(0.15264423811518624)),
 (331, np.float64(0.06989224843857954)),
 (332, np.float64(0.04185621763013559)),
 (333, np.float64(0.04975015482949439)),
 (334, np.float64(0.08959386479388606)),
 (335, np.float64(0.1501102354482201)),
 (336, np.float64(0.0)),
 (337, np.float64(0.024292691373250283)),
 (338, np.float64(0.1504165407034675)),
 (339, np.float64(0.067319034727059)),
 (340, np.float64(0.06136363931290952)),
 (341, np.float64(0.09854883935542114)),
 (342, np.float64(0.10569547524052622)),
 (343, np.float64(0.06871960519025327)),
 (344, np.float64(0.08484641346488767)),
 (345, np.float64(0.03551179061517312)),
 (346, np.float64(0.0587909433219889)),
 (347, np.float64(0.030355664343854866)),
 (348, np.float64(0.05360111849318519)),
 (349, np.float64(0.08709471678751979)),
 (350, np.float64(0.04487707967388422)),
 (351, np.float64(0.0)),
 (352, np.float64(0.15472949277033618)),
 (353, np.float64(0.11976421449443544)),
 (354, np.float64(0.0539058397789098)),
 (355, np.float64(0.2365229638564436)),
 (356, np.float64(0.14347518090486763)),
 (357, np.float64(0.0)),
 (358, np.float64(0.03863750723270766)),
 (359, np.float64(0.06716586266345263)),
 (360, np.float64(0.0)),
 (361, np.float64(0.041290993742935655)),
 (362, np.float64(0.14938828623857875)),
 (363, np.float64(0.07854440889985266)),
 (364, np.float64(0.005513529161379863)),
 (365, np.float64(0.15020573241645507)),
 (366, np.float64(0.045582760925275315)),
 (367, np.float64(0.0)),
 (368, np.float64(0.10783950141028917)),
 (369, np.float64(0.0)),
 (370, np.float64(0.041060592816787644)),
 (371, np.float64(0.0)),
 (372, np.float64(0.04950754484810965)),
 (373, np.float64(0.121329553158369)),
 (374, np.float64(0.08525860864343157)),
 (375, np.float64(0.040642972373616984)),
 (376, np.float64(0.0990296171856622)),
 (377, np.float64(0.08594319484912816)),
 (378, np.float64(0.0)),
 (379, np.float64(0.13198505270815336)),
 (380, np.float64(0.12463922508366751)),
 (381, np.float64(0.10982695939168732)),
 (382, np.float64(0.04014971016384018)),
 (383, np.float64(0.05646305195630917)),
 (384, np.float64(0.041161717855159485)),
 (385, np.float64(0.1373830843261975)),
 (386, np.float64(0.018472664864809255)),
 (387, np.float64(0.0)),
 (388, np.float64(0.04925229958851876)),
 (389, np.float64(0.09103608227676807)),
 (390, np.float64(0.0)),
 (391, np.float64(0.047820793106302786)),
 (392, np.float64(0.02720033866505913)),
 (393, np.float64(0.14815552659398531)),
 (394, np.float64(0.11301544344802604)),
 (395, np.float64(0.052491845040570514)),
 (396, np.float64(0.11601387526438581)),
 (397, np.float64(0.05559379508861256)),
 (398, np.float64(0.04388675011982164)),
 (399, np.float64(0.07614991623295202)),
 (400, np.float64(0.08978405704974649)),
 (401, np.float64(0.03532111349379949)),
 (402, np.float64(0.0)),
 (403, np.float64(0.13614592050871155)),
 (404, np.float64(0.09890758105430383)),
 (405, np.float64(0.12005957995148396)),
 (406, np.float64(0.06325285301751386)),
 (407, np.float64(0.04349249574014254)),
 (408, np.float64(0.0)),
 (409, np.float64(0.05316271787472345)),
 (410, np.float64(0.09199731803564798)),
 (411, np.float64(0.053212777299595025)),
 (412, np.float64(0.04540428812053456)),
 (413, np.float64(0.19315673058114086)),
 (414, np.float64(0.11394485634440187)),
 (415, np.float64(0.09133846941730697)),
 (416, np.float64(0.19058761881047576)),
 (417, np.float64(0.04347653897170489)),
 (418, np.float64(0.26043350404519483)),
 (419, np.float64(0.15252893595505246)),
 (420, np.float64(0.03708530450777944)),
 (421, np.float64(0.1372984773848736)),
 (422, np.float64(0.06795495074735679)),
 (423, np.float64(0.041255936044125634)),
 (424, np.float64(0.0658700777298896)),
 (425, np.float64(0.13153979683766578)),
 (426, np.float64(0.055145703186438744)),
 (427, np.float64(0.15284948690134853)),
 (428, np.float64(0.03437850149029785)),
 (429, np.float64(0.09867017961563439)),
 (430, np.float64(0.09035727383213546)),
 (431, np.float64(0.0037168648997226855)),
 (432, np.float64(0.04817883837175242)),
 (433, np.float64(0.05964774832930702)),
 (434, np.float64(0.10938139647582185)),
 (435, np.float64(0.09583110991741145)),
 (436, np.float64(0.09623985029579489)),
 (437, np.float64(0.040043107083280204)),
 (438, np.float64(0.06624886952263662)),
 (439, np.float64(0.05071691154700442)),
 (440, np.float64(0.15885387806487417)),
 (441, np.float64(0.04836698454663842)),
 (442, np.float64(0.0)),
 (443, np.float64(0.18812758219200168)),
 (444, np.float64(0.13591048547953927)),
 (445, np.float64(0.0525656021390133)),
 (446, np.float64(0.11747551422085854)),
 (447, np.float64(0.08148164093704399)),
 (448, np.float64(0.13283776576057466)),
 (449, np.float64(0.0)),
 (450, np.float64(0.09758141205573112)),
 (451, np.float64(0.08711967652033026)),
 (452, np.float64(0.02132386956109464)),
 (453, np.float64(0.0)),
 (454, np.float64(0.08680456715826985)),
 (455, np.float64(0.054607333284564796)),
 (456, np.float64(0.11039363592960164)),
 (457, np.float64(0.06394133781804279)),
 (458, np.float64(0.029627338748316436)),
 (459, np.float64(0.05464880282578916)),
 (460, np.float64(0.039270543838185706)),
 (461, np.float64(0.06125578352731334)),
 (462, np.float64(0.1906741528514433)),
 (463, np.float64(0.14766333386453184)),
 (464, np.float64(0.12839620810973773)),
 (465, np.float64(0.0)),
 (466, np.float64(0.11214012713965582)),
 (467, np.float64(0.08023520088651565)),
 (468, np.float64(0.03773154674365849)),
 (469, np.float64(0.04279678798044113)),
 (470, np.float64(0.17654166459351425)),
 (471, np.float64(0.0)),
 (472, np.float64(0.10953853306311577)),
 (473, np.float64(0.0)),
 (474, np.float64(0.08715300845336112)),
 (475, np.float64(0.0)),
 (476, np.float64(0.0874426069321224)),
 (477, np.float64(0.0)),
 (478, np.float64(0.04020861015194954)),
 (479, np.float64(0.045513481077980394)),
 (480, np.float64(0.04796382082030412)),
 (481, np.float64(0.18594225465010403)),
 (482, np.float64(0.0)),
 (483, np.float64(0.08078488794933217)),
 (484, np.float64(0.05440312695354405)),
 (485, np.float64(0.0)),
 (486, np.float64(0.21093947720328232)),
 (487, np.float64(0.024365950871756543)),
 (488, np.float64(0.07549605972820336)),
 (489, np.float64(0.041826724129275114)),
 (490, np.float64(0.09341994070090867)),
 (491, np.float64(0.05907026285602983)),
 (492, np.float64(0.0)),
 (493, np.float64(0.0)),
 (494, np.float64(0.11215607905204421)),
 (495, np.float64(0.09481724891047125)),
 (496, np.float64(0.06406324978447211)),
 (497, np.float64(0.10906973286053935)),
 (498, np.float64(0.0)),
 (499, np.float64(0.11613161649107337)),
 (500, np.float64(0.05181828128506273)),
 (501, np.float64(0.09457348520466713)),
 (502, np.float64(0.07271500213795182)),
 (503, np.float64(0.1524196454939654)),
 (504, np.float64(0.14167446943842418)),
 (505, np.float64(0.14572896440412786)),
 (506, np.float64(0.04633043304538435)),
 (507, np.float64(0.013148768430796032)),
 (508, np.float64(0.037163029342891986)),
 (509, np.float64(0.055560922627409026)),
 (510, np.float64(0.13941028177220366)),
 (511, np.float64(0.03293400791580725)),
 (512, np.float64(0.11876917259848269)),
 (513, np.float64(0.03243846283407315)),
 (514, np.float64(0.08786235244220587)),

In [ ]:
#Sort by similarity (descending)
sorted(list(enumerate(similarity_scores[index])),
       key=lambda x: x[1],
       reverse=True)

In [ ]:
sorted(list(enumerate(similarity_scores[index])),
       key=lambda x: x[1],
       reverse=True)[1:]

Top 3–5 similar books lo
top_books = [(2, 0.85), (4, 0.76), (3, 0.40)]
📌 STEP 8: Ab real book names nikalo
pt.index[2]
pt.index[4]
pt.index[3]

Original dataset se details lo
books[books['Book-Title'] == pt.index[2]]

In [ ]:
def recommend(book_name):
    # index fetch
    index = np.where(pt.index==book_name)[0][0]
    similar_items = sorted(list(enumerate(similarity_scores[index])),key=lambda x:x[1],reverse=True)[1:5] #👉 index + similarity pair
    
    data = []
    for i in similar_items:
        item = []
        temp_df = books[books['Book-Title'] == pt.index[i[0]]]
        item.extend(list(temp_df.drop_duplicates('Book-Title')['Book-Title'].values))
        item.extend(list(temp_df.drop_duplicates('Book-Title')['Book-Author'].values))
        item.extend(list(temp_df.drop_duplicates('Book-Title')['Image-URL-M'].values))
        
        data.append(item)
    
    return data

In [ ]:
recommend('1984')

In [ ]:
books.drop_duplicates('Book-Title')

In [ ]:
import pickle

In [ ]:
pickle.dump(pt,open('pt.pkl','wb'))
pickle.dump(books,open('books.pkl','wb'))
pickle.dump(similarity_scores,open('similarity_scores.pkl','wb'))

In [ ]:
num_rating_df = ratings_with_name.groupby('Book-Title').count()['Book-Rating'].reset_index()
num_rating_df.rename(columns={'Book-Rating':'num_ratings'},inplace=True)
num_rating_df

In [ ]:
avg_rating_df = ratings_with_name.groupby('Book-Title').mean()['Book-Rating'].reset_index()
avg_rating_df.rename(columns={'Book-Rating':'avg_rating'},inplace=True)
avg_rating_df

In [ ]:

print(ratings_with_name['Book-Rating'].dtype)
print(ratings_with_name['Book-Rating'].head(10))
#Agar dtype object dikhe ya values mein quotes hoon — yehi problem hai.

In [ ]:
popular_df = num_rating_df.merge(avg_rating_df,on='Book-Title')
popular_df

User enters book name
        ↓
FastAPI receives request
        ↓
Recommendation logic runs
        ↓
JSON response returns